name: Daily Scheduled Task

on:
  schedule:
    # Запуск каждый день в 00:00 (UTC)
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Send message
        run: python scripts/send_message.py
